### ISSUE TITLE
(feat) Add required libs to project

### ISSUE THREAD

**Issue by eprislac** [Vets-Who-Code/vwc_fng_tracker#3]
### DESCRIPTION # 
Install required libraries

### TASKS # 
- [x] re-bootstrap FE using `create-react-app` using `--typescript` flag
- [x] ~install jest (testing library)~ included with `create-react-app`
- [x] install dgraph-js-http (database adapter)
- [x] install bootstrap (maybe)
- [x] install fontawesome (icon library)
- [x] install tslint (code linter)
- [x] install travis-ci integration (CI)
- [x] install typedoc (documentation generator)
- [x] install storybook (ui testing)
